### ISSUE TITLE
Winsorization (obrigatorio)

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [AdaptaBrasil/reprodutibilidade#11]
Reproduzir a Winsorization usada pelo AdaptaBrasil. Parece que a funcao do coinR não é exatamente a que é usada atualmente na planilha do Adapta.

**Comment by netebarreto** [comment]
![Comparação_Winso](https://github.com/user-attachments/assets/640dfd2d-3ce1-4e53-89cd-5ca0acfd2517)
